# Generated by Django 4.2.7 on 2025-09-29 07:24

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SKU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique SKU code",
                        max_length=20,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Product name",
                        max_length=200,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        help_text="Manufacturer name",
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "pack_size_kg",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Pack size in kilograms",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Product description"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the SKU is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SKU",
                "verbose_name_plural": "SKUs",
                "db_table": "catalog_sku",
                "ordering": ["name"],
            },
        ),
    ]
